### ISSUE TITLE
Residual energy bar incorrectly wasted

### ISSUE THREAD

**Issue by AlbertKleinstein** [pvpoke/pvpoke#1]
It looks like after a charge move is used the energy is "reset" to zero.

Instead, the residual energy due to non-integer number of fast moves needed to charge a charge move should be saved and added to the energy accumulated for the next charge move.

Example: in http://pvpoke.com/battle/1500/skarmory/marshtomp/12/031/031/ Marshtomp should have the 2nd Surf charged after 9 Mud Shots (9 x 9 = 81 > 80) but instead it waits until after the 10th Mud Shot.

Possible fix: in Battle.js, at line 402, instead of 

`attacker.energy = 0;`

you should put 

`attacker.energy -= move.energy;`

**Comment by pvpoke** [comment]
Thanks for the very clear explanation, example, and solution for the issue! This was really helpful.

I tested your fix and Marshtomp does now use its 2nd Surf after 9 Mud Shots. I have the updated code live and in the latest release.
