### ISSUE TITLE
Feature Request: Add pokemon name to GET path for rankings to filter to that pokemon

### ISSUE THREAD

**Issue by personjerry** [pvpoke/pvpoke#103]
I find myself searching `pvpoke rankings [pokemon name]` pretty often on Google. If we create GET urls that prepopulate the "search" field with the pokemon, then these will be indexed and visible as search results :)

Ideally the rank number could even be included in the title or body so it's easily viewable right from the Google result, but that leads people to visit the site less 🤷‍♂️

**Comment by pvpoke** [comment]
Thanks for this, I've been meaning to do this for a while! The Pokemon's name is now indexed in the page title and meta description, so hopefully results should pop up in Google soon.

**Comment by personjerry** [comment]
@pvpoke Are those URLs linked from anywhere? It looks like most of them haven't been indexed yet.
