### ISSUE TITLE
strange results from changing the second charged move

### ISSUE THREAD

**Issue by ltleelim** [pvpoke/pvpoke#113]
I've been looking at the 1 shield matchups of Altaria vs Shadow Magneton.

When Altaria has no second charged move:
https://pvpoke.com/battle/1500/altaria/magneton_shadow/11/0-3-0/2-4-1/

When Altaria has Dragon Pulse:
https://pvpoke.com/battle/1500/altaria/magneton_shadow/11/0-3-2/2-4-1/

When Altaria has Dazzling Gleam:
https://pvpoke.com/battle/1500/altaria/magneton_shadow/11/0-3-1/2-4-1/

Altaria is only using Sky Attack, but the results are different in each case. In particular, PvPoke is choosing different times to use Sky Attack in each case. Could you please explain why it is behaving differently in each case?

**Comment by brandon-lu** [comment]
I think in each case the Altaria is building up to the 2nd charge move before throwing in order to bait. Since each charge move has a different energy cost, this affects the charge move throwing behavior.

**Comment by ltleelim** [comment]
The previous results were illogical because Altaria could win using only Sky Attack, but was delaying the charge move in some cases and losing. As Brandon Lu noted, it may have been due to baiting. Or it may have been due to some other unexplained reason.

In any case, the problem was fixed with the v1.17.0 update. The three cases listed above now produce the same results.

It would have been nice if PvPoke had commented on this issue.
