### ISSUE TITLE
new algorithm hangs in some cases

### ISSUE THREAD

**Issue by ltleelim** [pvpoke/pvpoke#118]
The new algorithm hangs in some cases. The code takes so long to execute that it appears to be in an infinite loop.

Tested in Firefox and Chrome. Firefox by default doesn't wait as long and pops up notifications more frequently. Chrome by default waits longer for it to execute. If you keep pressing Wait, then it's possible for some of the easier cases to finish executing.

https://pvpoke.com/battle/2500/giratina_origin/blissey/11/1-3-2/1-3-2/

https://pvpoke.com/battle/2500/melmetal/blissey/11/0-3-4/1-3-2/

https://pvpoke.com/battle/2500/melmetal/giratina_origin/22/0-3-4/1-3-2/

https://pvpoke.com/battle/2500/melmetal/nidoqueen/11/0-3-4/1-2-4/

https://pvpoke.com/battle/2500/melmetal/nidoqueen_shadow/00/0-3-4/1-2-5/

https://pvpoke.com/battle/2500/giratina_origin/obstagoon/22/1-3-2/0-4-2/

**Comment by pvpoke** [comment]
Thanks so much for providing these examples, I'll investigate what's happening here.

**Comment by pvpoke** [comment]
I've just pushed an update that improves the efficiency of simulating these matchups. Let me know if you encounter any other issues!

**Comment by ltleelim** [comment]
Thanks, it does calculate these matchups much faster and doesn't hang anymore.

However, I've noticed that some simulation results have changed. (I keep spreadsheets of matchups for my teams.) This makes me wonder if the accuracy of the results has decreased.
