### ISSUE TITLE
new algorithm only uses fast moves in some 2 shield scenarios

### ISSUE THREAD

**Issue by ltleelim** [pvpoke/pvpoke#119]
The new algorithm only uses fast moves in some 2 shield scenarios. This seem especially suspect with Giratina (Origin) because its usual moves are all Ghost type so a charged move should do more damage and end the battle faster.

https://pvpoke.com/battle/1500/giratina_origin/darmanitan_galarian_standard/22/1-3-2/1-1-4/

https://pvpoke.com/battle/2500/giratina_origin/espeon/22/1-3-2/0-4-2/

https://pvpoke.com/battle/2500/snorlax/espeon/22/0-1-2/0-4-2/

**Comment by pvpoke** [comment]
Thanks reporting the issue. I just pushed an update which should resolve this but let me know if you come across any other scenarios.

**Comment by ltleelim** [comment]
Confirmed that it appears to be fixed. I had one other case and that's fixed too. Thanks!
