### ISSUE TITLE
NaN in Marsh Ranking

### ISSUE THREAD

**Issue by gab07** [pvpoke/pvpoke#122]
<img width="770" alt="imagen" src="https://user-images.githubusercontent.com/11811236/97055997-8ac89b80-154d-11eb-900e-46a347f5f061.png">

**Comment by bedwar14** [comment]
While this issue doesn't appear to be occurring any longer for Cloyser in the Marsh cup,  I suspect this occurs when data hasn't been entered for the Meta yet.  Could probably add either 0%  or -- for undefined values.
