### ISSUE TITLE
Beheeyem moves incorrect

### ISSUE THREAD

**Issue by PizzaMan79** [pvpoke/pvpoke#124]
In league rankings for great league,  the moves with beheeyem were incorrect. The preferred moves were displayed correctly,  but when opening for more info, this list of moves with % preferred contained false moves. After switching to ultra leagues, the moves were correct. Using adblock browser on Android. I didn't take a screenshot and i haven't yet managed to replicate. I'll of course be aware of the conditions and make a screenshot next time it happens.

**Comment by PizzaMan79** [comment]
Here are some screenshots. I was in great league rankings,  entered a search term "mewt" and then switched to ultra and the to master league with the search term still active.
![Screenshot_20201030-165525_Adblock Browser](https://user-images.githubusercontent.com/73500837/97727973-4733db80-1ad1-11eb-9682-13508bf926b9.jpg)
![Screenshot_20201030-165517_Adblock Browser](https://user-images.githubusercontent.com/73500837/97727975-47cc7200-1ad1-11eb-9cab-1c21252d0a5d.jpg)
![Screenshot_20201030-165508_Adblock Browser](https://user-images.githubusercontent.com/73500837/97727978-48650880-1ad1-11eb-9b77-1838f5ab3479.jpg)
![Screenshot_20201030-165440_Adblock Browser](https://user-images.githubusercontent.com/73500837/97727980-48fd9f00-1ad1-11eb-82e8-f485b146a4e0.jpg)

**Comment by pvpoke** [comment]
Hey, thanks for posting this. I've resolved the issue related to this bug. Let me know if you come across anything else.

**Comment by PizzaMan79** [comment]
Wow, i never expected someone to respond so quickly, let alone look into the issue, let alone fix it! I'll report back if the issue pops up again, but I'm confident it won't :-)
