### ISSUE TITLE
'null' in Master Premier overall rating

### ISSUE THREAD

**Issue by secretsciencelab** [pvpoke/pvpoke#127]
Hi Matt,

In your latest Rankings update, the Master Premier overall scores were broken:
https://pvpoke.com/rankings/premier/10000/overall/

See the rightmost column -- everything is 'null'

**Comment by secretsciencelab** [comment]
You can also see the same problem here in the .json:
https://raw.githubusercontent.com/pvpoke/pvpoke/master/src/data/rankings/premier/overall/rankings-10000.json

E.g.
"score":null,"scores":[null,91.9]},

**Comment by XXVI-III-CX** [comment]
It appears to be fixed, do you see any further issue with this?

**Comment by secretsciencelab** [comment]
It's fixed! Thank you
