### ISSUE TITLE
Pyroar Fast Move

### ISSUE THREAD

**Issue by mprenaca** [pvpoke/pvpoke#133]
Male Pyroar is not able to learn the fast move ember by either regular or elite fast tm. I'm not sure if this information came from source code, but out of the 3(litleo, M/F Pyroar) only litleo is able to learn ember. I have footage of using several tms, and if you attempt to use an elite fast tm you can see for yourself that teaching ember is not an option.

**Comment by pvpoke** [comment]
Thanks for letting me know! I have Ember removed from Pyroar now.
