### ISSUE TITLE
Custom Rankings Species Inclusion problem

### ISSUE THREAD

**Issue by azum4roll** [pvpoke/pvpoke#136]
Two problems:
1. Listing a base Pokemon includes Shadow and XL versions too, when only exclusion should work like that.
2. Cannot include just a Shadow or XL Pokemon anymore.

![image](https://user-images.githubusercontent.com/14953746/109122033-fd0eee00-7782-11eb-85a9-92403372c806.png)

**Comment by pvpoke** [comment]
Hey, thanks for the heads up. I've fixed this so inclusion doesn't include XL and Shadow versions of the same Pokemon, and you can include only the Shadow or the XL.
