### ISSUE TITLE
Leagues not appearing in ranks

### ISSUE THREAD

**Issue by gilhv** [pvpoke/pvpoke#137]
as of 2/25
Premiere (all) and Master League (Ultra) are not available.
This should be a basic feature for trainers to check ranks, regardless of what cups are planned for the season.
<img width="330" alt="Screen Shot 2021-02-25 at 10 57 16 AM" src="https://user-images.githubusercontent.com/79663127/109203580-2f0b5a80-7759-11eb-92f2-0df0d02b22bd.png">

**Comment by pvpoke** [comment]
Hey, thanks for the post. If you're looking for resources for Master League Premier Cup, you can use the [Custom Rankings tool](https://pvpoke.com/custom-rankings/) to generate rankings for any past or potential format.  The [Premier Cup meta list](https://pvpoke.com/battle/multi/10000/custom/metagross/11/0-3-1/2-1/premier/) is also still available for you to check the performance of individual Pokemon.

While I would love to support rankings for every format, it's unfortunately not a feasible or basic feature. Each ranking list represents a significant amount of time adjusting movesets and weightings over the lifetime of the format. I must update them individually when new Pokemon are released, new moves are added, or move updates occur. With the limited time I have, I have to make careful choices about how I spend my time and unfortunately that means some sacrifices to support the current and active formats. The tools exist if you want to explore other formats on your own. Thanks for understanding!
