### ISSUE TITLE
No switch timer in training battles

### ISSUE THREAD

**Issue by Orangegrarrl89** [pvpoke/pvpoke#143]
I was just doing some training battles and noticed that there is no switch timer in the battles.  This basically locks the player out from switching again for the rest of the battle, even after one minute has elapsed.  I think maybe you gave people the option to select a 30 or 60 second switch timer a few days ago, but the timer seems to be gone entirely since you tried to revert it back to 60 seconds.  Anyway, I love the site & thanks for all you do!

**Comment by pvpoke** [comment]
Thanks for letting me know! I've taken a look and haven't been able to reproduce the issue. Could you let me know if you experience this in every training battle, or if there might be some kind of trigger?

**Comment by Orangegrarrl89** [comment]
hmm, it seems to be working now.  not sure what was going on last night, but I'm glad it's fine.  Thx for the quick response!
