### ISSUE TITLE
politoed related pokemon has double under score in id

### ISSUE THREAD

**Issue by Bruceychen** [pvpoke/pvpoke#147]
Hi pvpoke,

The latest release version has this error on https://pvpoke.com/train/analysis/:
![01](https://user-images.githubusercontent.com/23501240/117263306-bb867780-ae84-11eb-99f6-940824b49ad1.png)

And checked with IDE for all files of the pvpoke project:
![02](https://user-images.githubusercontent.com/23501240/117263647-10c28900-ae85-11eb-8344-31659a43f737.png)

**Comment by pvpoke** [comment]
Thank you! I have this fixed now!
