### ISSUE TITLE
Dragalge omitted from the top performers list

### ISSUE THREAD

**Issue by ckortendick** [pvpoke/pvpoke#155]
Seeing how you yourself used it, find it kinda odd.

**Comment by pvpoke** [comment]
Thanks for the post! Which Pokemon appear in the top performers list depends on the Pokemon people train with. I filter the results by volume so a Pokemon may not appear in the top performers list unless it has a sufficient sample size of training data. Dragalge unfortunately didn't make the cut this time around but maybe it will be popular enough to appear in future data.
