### ISSUE TITLE
Pokemon with deselected charged moves still use charged moves in the simulation

### ISSUE THREAD

**Issue by pvpoke** [pvpoke/pvpoke#16]
This issue was reported on Discord. It appears that if both charged moves are set to "none", a Pokemon will still use Charged Moves in the simulation. I've tested this in a number of cases and can't seem to reproduce the error, so any help would be appreciated!

A separate but related issue is that links to battles where Pokemon have no charged moves don't work correctly, and give that Pokemon a charged move. My hunch is this is just an issue with how the page processes the URL parameters, so I'll be taking a look at that.

**Comment by davidpeden3** [comment]
I am able to repro using both desktop and mobile Safari. The issue does not happen on desktop or mobile Chrome.

**Comment by pvpoke** [comment]
Thanks for your help with this! I identified the issue as well as fixed the link issue in [v.1.3.0](https://github.com/pvpoke/pvpoke/releases/tag/v1.3.0).

When Pokemon begin a battle, each recalculates its move damage and determines its "best charged move" based on damage per energy. This best charged move is referenced for primary decision making, and the other charged move is referenced in secondary scenarios.

What caused this issue is that the "best charged move" would be set after a regular battle, but would never unset if a user deselected all Charged Moves. This caused the Pokemon to continue using its best charged move in subsequent battles.

The solution is just a couple lines setting the best charged move to null if no Charged Moves are selected.
