### ISSUE TITLE
Custom Rankings are now missing for Little Leauge/500 CP

### ISSUE THREAD

**Issue by hstyer** [pvpoke/pvpoke#178]
There is usually an option to select Little League when generating custom rankings, but I noticed today that it had been removed.
![image](https://user-images.githubusercontent.com/98130969/150440456-11af4962-3002-49c8-b185-28a6ae07fd40.png)

**Comment by pvpoke** [comment]
Thanks for posting this, there was a previous issue that caused the Little Cup option to intermittently disappear as well. I found the source of the issue and it should be fixed now. Let me know if you run into any problems!
