### ISSUE TITLE
Element Cup Training Battle not working correctly

### ISSUE THREAD

**Issue by JFlowx** [pvpoke/pvpoke#189]
The element cup training battle is not working correctly. 

Pokemon selected for teams are defaulted to great league cp/stats.

When battling with selected pokemon as is, great league pokemon are the opponents.

After changing stats and levels of selected pokemon to be in allowed range, when selecting the "battle" button nothing happens...

![PVPokeError-2](https://user-images.githubusercontent.com/72576860/182265504-debd2251-3c71-4ce0-b2cd-00de8de3b055.jpg)
![PVPokeError-1](https://user-images.githubusercontent.com/72576860/182265506-d3a130df-a6a3-4528-a0a0-6b003a53e77b.jpg)

**Comment by pvpoke** [comment]
Thanks for posting the issue! I have this resolved now.
