### ISSUE TITLE
Training Battles - Element Cup not working

### ISSUE THREAD

**Issue by JFlowx** [pvpoke/pvpoke#192]
Hello,

The training battle element cup is not working. I am unable to add any pokemon. Also I think it is supposed to be the little jungle remix?

Thanks!

**Comment by pvpoke** [comment]
Element Cup training isn't intended to be active right now, I'll get that listing removed. Due to the 1 week rotations of the themed cups, I only plan to support open league training at this time.

**Comment by JFlowx** [comment]
I understand thank you for looking into that.

Any chance you can make another generalized “little cup” league where we can then enter our own teams to face?

Thank you
