### ISSUE TITLE
XSS vulnerabilities

### ISSUE THREAD

**Issue by migg24** [pvpoke/pvpoke#21]
Hi there!

There are multiple cross-site-scripting issues in your code that attackers can use to attack your users. You state you like to keep it simple and not introduce fancy frameworks but you also removed the seatbelts to stay with your readme language. I did not do a thorough analysis, only tried some basic old payloads.

Would you like me to disclose the vulnerabilities here or chat about it somewhere else? I also could help mitigating them if you accept contributions in that regard.

**Comment by pvpoke** [comment]
Thanks for the report! Would Discord or email work for you for discussing the details? I'd be happy to receive any contributions to resolve the issues you've described.

**Comment by migg24** [comment]
Sure discord would work, which server?
