### ISSUE TITLE
Primals not updated in Speculative setting

### ISSUE THREAD

**Issue by ItsWaylonger** [pvpoke/pvpoke#220]
When I'm in training battles I still see the old stats reflected for Primal Groudon and Kyogre (9% nerf max CP 5910) instead of the accurate ones specifically when I switch the website setting for Mega Evolutions (Speculative). They have accurate stats under the default setting.

**Comment by pvpoke** [comment]
Thanks for letting me know! I've removed the duplicate stat blocks from the speculative mega file and I'll have this pushed with the next release.
