### ISSUE TITLE
Dragonite Dragon Claw Spec wrong

### ISSUE THREAD

**Issue by thehart27** [pvpoke/pvpoke#232]
Dragonite has Dragon Claw as a charged attack, and on Pvpoke it shows that it does 60 Damage, on Pokémon Go it only does 50 Damage, in raids, pvp, and trainer battles. 

![image](https://user-images.githubusercontent.com/127585415/224469995-81ecc8c5-7822-4645-9d17-4e3b5e19c19a.png)

![image](https://user-images.githubusercontent.com/127585415/224470002-f0a949a9-ed7b-49a6-beef-5092e0866ec8.png)

**Comment by pvpoke** [comment]
Thanks for the post! The move stats listed in the rankings include the x1.2 Same Type Attack Bonus so the figure there is correct (50 x 1.2 = 60).

You can check the base power of moves from the Moves page if you want to see the same numbers that are listed in-game.

https://pvpoke.com/moves/charged/
