### ISSUE TITLE
shadow claw

### ISSUE THREAD

**Issue by raulken78** [pvpoke/pvpoke#24]
is a 6dps and not 4dps

https://pvpoke.com/battle/1500/linoone-40-7-7-7-4-4-0/minun-40-6-6-6-4-4-0/11/0-2-3/1-3-1/

**Comment by pvpoke** [comment]
Thanks for the report! You're right, Shadow Claw does have 6 power. That number gets put through a formula that looks like this for the final damage calculation:

`damage = floor(power * stab * effectiveness * (attack / defense) * pvp multiplier * 0.5) + 1`

* Power - base power of the attack
* STAB - same type attack bonus, x1.2 if the Pokemon has the same type as the move
* Effectiveness - x1.6 for super effective, x.625 for not very effective
* Attack - the attacker's Attack stat
* Defense - the defender's Defense stat
* PvP Multiplier - all damage in PvP is multiplied by x1.3

Using the stats for the Linoone and Minun above, this gives us:

`damage = floor(6 * 1 * 1 * (117.7/122.7) * 1.3 * 0.5) +1`

And this all comes out to the 4 damage you see in the simulation.
