### ISSUE TITLE
Team builder function issue on Tier points and Eligible pokemons of Cliffhanger cup

### ISSUE THREAD

**Issue by Bruceychen** [pvpoke/pvpoke#240]
Hi,
the Team builder function has below 2 issues:
1. Alolan Grimer and Kommo-o are supposed to be 1 point tier but are currently assigned 0 points.
2. Buzzwole is marked as "A Pokemon may have too low stats or be ineligible.", but it should be assigned as B tier

above data are refer to Cliffhanger website:
https://www.stadiumgaming.gg/cliffhanger-calculator

https://pvpoke.com/team-builder/cliffhanger/1500/grimer-m-2-4-1%2Ckommo_o-m-0-3-2%2Cbuzzwole-m-0-4-2

Thanks
![Fox7kKlWIAQ6BBF](https://user-images.githubusercontent.com/23501240/233759712-304f0a17-aa34-4bb7-90a5-8da920d5ae2b.png)

![截圖 2023-04-22 上午11 29 44](https://user-images.githubusercontent.com/23501240/233759780-9a0b865e-bcd3-4cc9-a0c4-0bd5d94e34ea.png)

**Comment by pvpoke** [comment]
Thanks for posting! I have this fixed in the latest update.
