### ISSUE TITLE
Adjust cursor position out of dmg number on left-hand side float template

### ISSUE THREAD

**Issue by Bruceychen** [pvpoke/pvpoke#250]
Hi,

After battle simulation, the dmg number on left-hand side float template will be blocked by mouse cursor:
![image](https://github.com/pvpoke/pvpoke/assets/23501240/f18941b7-4067-41a5-bbb7-1d216fa95f56)

but ok on the right:
![image](https://github.com/pvpoke/pvpoke/assets/23501240/1e1fea64-054f-482e-9a45-a0e3ab90e13b)

is it ok to adjust the cursor position?

Thanks

**Comment by pokedokeyoh** [comment]
Thanks for raising this. If the cursor position could be moved, that would be amazing.

**Comment by pvpoke** [comment]
Sorry for the late reply, and thanks for posting this! This should be resolved in the latest update.
