### ISSUE TITLE
Mega Tyranitar/Mega Rayquaza

### ISSUE THREAD

**Issue by ItsWaylonger** [pvpoke/pvpoke#256]
In Training Battles, Mega Tyranitar is missing from Default setting and Mega Rayquaza appears twice in Mega Evolutions (Speculative) setting, both with the old 9% nerf stats. The other settings have the correct 3% nerf stats.

**Comment by pvpoke** [comment]
Thanks for reporting the issue, I've added Mega Ttar and the Mega Rayquaza issue should be fixed now.
