### ISSUE TITLE
Abbreviation needed to disambiguate SHADOW_SNEAK and SANDSEAR_STORM

### ISSUE THREAD

**Issue by drnobody42** [pvpoke/pvpoke#265]
If I understand correctly, when generating string representations of move sets (e.g., "Swampert MS+HC/Eq"), the move details in https://github.com/pvpoke/pvpoke/blob/a31cbae1a148fcadf5bea5b71010e879e4a361b6/src/data/gamemaster/moves.json#L2229 add an abbreviation if auto-generation doesn't result in a unique name. Currently it seems that both SHADOW_SNEAK and SANDSEAR_STORM resolve to SS.

**Comment by pvpoke** [comment]
Thanks for reporting this, I've given SANDSEAR_STORM the abbreviation "SSt".
