### ISSUE TITLE
Greninja Charge moves - NightSlash

### ISSUE THREAD

**Issue by ReverentSole** [pvpoke/pvpoke#268]
The charge moves are showing Night Slash as an option for Greninja however I don’t see that as an in-game option, even with an Elite TM.

**Comment by pvpoke** [comment]
Hey, thanks for the post. I can confirm that Greninja indeed learns Night Slash - I have it myself and I've encountered it in the past week! When you use an Elite TM to view a Pokemon's movepool, make sure you progress to the screen where you select the new move. (If the Pokemon is double-moved, it prompts you to select a move the Pokemon currently knows.)
