### ISSUE TITLE
[Question] How is the pokemon.json file initially generated?

### ISSUE THREAD

**Issue by jeffsawatzky** [pvpoke/pvpoke#269]
I see this file:
https://github.com/pvpoke/pvpoke/blob/master/src/data/parse.php

Which seems to read from a `gamemaster-app.json` file that doesn't exist, and it also just outputs to the console. I assume it comes from pokeminers?

I'm trying to figure out how to parse the pokeminers file from:
https://github.com/PokeMiners/game_masters/blob/master/latest/latest.json
and remove the extra stuff, and I'm trying to see how you do it. For instance, the pokeminers file has multiple forms for pokemon like Shellos, but pvpoke only has the one form. Then there are pokemon like Darmanitan that have multiple forms which you have, but you somehow ignore the formless V0555_POKEMON_DARMANITAN template.

So, do you just manage the file manually and not use the gamemaster file from the app? Or where does the code live which deals with the different templates and consolidating them into what you have?

Thanks!

**Comment by pvpoke** [comment]
Hey, thanks for the question! You're correct, I use the pokeminers file and run `parse.php` as needed and copy the console output into the `pokemon.json` file. There are a few other helper functions you can find in `js/Gamemaster.json` which I developed later on, such as `generateDefaultIVs()` and `updateShadowStatus()`.

I exclude any templates which contain "NORMAL", "SHADOW", and "PURIFIED" in their name as I have the above functions to generate the shadow versions myself with extra data. Other than that, I manually manage the templates and remove unnecessary duplicates, such as entries for Basculin, Shellos, etc. I made a mistake with Darmanitan and should have just used the "DARMANITAN" template so now "DARMANITAN_STANDARD" is kind of grandfathered in. Let me know if you have any other questions!

**Comment by jeffsawatzky** [comment]
@pvpoke Thanks!
I don't see any pokemonSettings templates with SHADOW or PURIFIED in their name, so that might be from older gamemaster data, and that filtering might not be needed anymore?

Do you have a list of things you manually remove (Basculin/Shellos/Furfruo/etc)? And is the reason you do this because their various forms are all basically the same (same base stats and moves)? Or, in otherwords, what is your criteria for clumping various forms into one? As for Darmantitan, I assume you use the "DARMANITAN_STANDARD" template and ignore the "DARMANITAN" one?

I am trying to write a small script for myself that will parse out my PokeGenie export (which I keep up to date with my pokedex in PoGo) and use the ranking data to try and find pokemon that I can get rid of, or which I should put effort into. And I need a way to map the pokemon from PokeGenie to your mapping.

Thanks again for answering my questions!
