### ISSUE TITLE
Feature Request: Search by move

### ISSUE THREAD

**Issue by efenderbosch** [pvpoke/pvpoke#27]
Not extremely useful for the Silph cups, but quite useful for custom draft leagues where you want to find, for example, the best razor leafer left in the draft.

Javascript isn't my strong point, but could probably contribute a pull request.

**Comment by efenderbosch** [comment]
maybe even support syntax like the game

@1fighting

@2psychic

etc

**Comment by pvpoke** [comment]
Hey, sorry for not responding to this earlier! That would definitely be a cool feature and something I'd like to include.

**Comment by efenderbosch** [comment]
I actually cut a fork to give it a go, but my javascript is woefully bad, so I kinda gave up.

Another search option might be @legacy or !@legacy.

**Comment by efenderbosch** [comment]
Just saw this was released! Awesome.
