### ISSUE TITLE
DPT*EPT is a not a good metric to show

### ISSUE THREAD

**Issue by jjung11** [pvpoke/pvpoke#281]
I recently noticed that Pvpoke shows DPT\*EPT for fast moves in 'Moves' page.
It is not a good metric, and should be replaced with something else. 
Unlike DPE and energy cost of charge move, DPT and EPT are not intertwined quantities.
For example, theoretically a move can have 0 DPT or EPT and still be a good move if the other value is high.
For substitute, I recommend DPT+4/3*EPT (https://www.reddit.com/r/TheSilphArena/comments/aks0tw/a_data_driven_master_league_analysis/), or at least DPT+EPT.

**Comment by pvpoke** [comment]
Hey, thanks for the feedback! I agree that it probably isn't the best metric to show, it was something I cobbled together quick to highlight the move changes. In that regard, it does pass the eye test and highlights moves we would expect to be strong. I would say DPT x EPT is better than DPT + EPT, and I'd like to avoid "magic math" that includes arbitrary numbers. In any case, I'll probably remove this column for the final version of the site.

**Comment by drnobody42** [comment]
I would agree that the product doesn't make sense...perhaps the standout example is lockon, which we all know is good yet is near the bottom of the rankings if you sort https://pvpoke.com/new-season/moves on the product.

In [this post](https://www.reddit.com/r/TheSilphArena/comments/1evynxg), I perform a "robust regression" (to decrease the influence of truly-bad moves, though even then I excluded a couple) of the stats of all fast moves, and came up with the following suggestion:
```
5*EPT + 4*DPT - T/6
```
where T = # of turns. It's not so different from the formula that @jjung11 recommends, except it also tries to account for the move duration. You'll also note from that 3d scatter plot, if the product were the thing that mattered, then the moves would probably be distributed along a hyperbola. They're definitely not distributed that way. They're not obviously on a plane, either, but by eye I think a planar fit is better than a hyperbola.

Also worth mentioning: why do we sometimes take products? The stat product has a strong justification: if you want to know who is going to win the battle, it comes down to whether you reduce your opponent's health faster *fractionally* than they do yours. Ignoring move power, the rate at which I reduce their HP is `(my attack) / (their defense)`, and this reduces their "normalized HP" by `(my attack) / ((their defense) * (their HP))`. Thus

```
my_win_ratio ∝ (my attack) / ((their defense) * (their HP))      /       (their attack) / ((my defense) * (my HP))

             = (my attack) * (my defense) * (my HP)              /       (their attack) * (their defense) * (their HP)

             = (my stat product)           /            (their stat product)
```

So products are well-justified in some cases, but not for assessing the tradeoffs in move quality.

**Comment by pvpoke** [comment]
I'm closing this as I have removed the DPT x EPT column from the latest update.
