### ISSUE TITLE
Drapion Misinformation 

### ISSUE THREAD

**Issue by Diablistical69** [pvpoke/pvpoke#282]
The site list Drapion as having 4 charged Attack Move available. I see only Two options...

**Comment by pvpoke** [comment]
Thanks for posting! The information on the website is correct. You can verify a Pokemon's Charged Attack options by using an Elite TM to preview its available moves. This menu doesn't show attacks the Pokemon already knows, so if you use this to preview the Charged Attack options for a Drapion which has 2 attacks unlocked, you will only see 2 of its 4 total attacks to select from.

**Comment by Diablistical69** [comment]
I've never heard of TMs not being available even when an Elite TM is used. What makes it unlocked for other Drapions?Sent from my Galaxy
-------- Original message --------From: Empoleon_Dynamite ***@***.***> Date: 9/4/24  8:12 AM  (GMT-05:00) To: pvpoke/pvpoke ***@***.***> Cc: Diablistical69 ***@***.***>, Author ***@***.***> Subject: Re: [pvpoke/pvpoke] Drapion Misinformation  (Issue #282) 
Thanks for posting! The information on the website is correct. You can verify a Pokemon's Charged Attack options by using an Elite TM to preview its available moves. This menu doesn't show attacks the Pokemon already knows, so if you use this to preview the Charged Attack options for a Drapion which has 2 attacks unlocked, you will only see 2 of its 4 total attacks to select from.
