### ISSUE TITLE
Where is the "turns" per move stored?

### ISSUE THREAD

**Issue by IncioMan** [pvpoke/pvpoke#283]
Hello,

first of all thank you for an amazing tool!

I am interested in getting the moves data and performing analysis. However, I am struggling to find the "turns" per move in the json data both in the repo and alo returned to the client 

In the screenshot the data for the Acid move, all values are contained in the response but not the number of turns.

Any suggestion in where that value is stored and how I can obtain it to add it to the gamemaster data json would be appreciated!

Thank you

<img width="1431" alt="Screenshot 2024-09-28 at 18 55 54" src="https://github.com/user-attachments/assets/a9f582a1-fc5c-4c85-8800-baa12936a101">

**Comment by pvpoke** [comment]
Hey, thanks for the question! This is a quirk from how I originally wrote the data, but I have turns stored as the "cooldown" property in milliseconds. Divide this by 500 and you'll get the number of turns for the move!
