### ISSUE TITLE
CustomRankingInterface.js - Duplicate "deleteFilterConfirm" function

### ISSUE THREAD

**Issue by sopgenorth** [pvpoke/pvpoke#284]
I'm just starting to "poke" around with the code base, and working to profile the site's javascript to see what might make sense for optimizations. 

Along the way here, I found the function "[deleteFilterConfirm](https://github.com/pvpoke/pvpoke/blob/2d6c44bf1f85dc4fe17d18c374f0ea8af6bc63ad/src/js/interface/CustomRankingInterface.js#L447)" to be defined twice in the same file. From what I understand with javascript, the last function defined is the one that will be be used. Is this duplicate functional intentional, or just a typo from time?

**Comment by pvpoke** [comment]
Thanks for the heads up, this is indeed a mistake! I'll get this updated.
