### ISSUE TITLE
Two formats simultaneously loaded into ranking list

### ISSUE THREAD

**Issue by ShaPhi7** [pvpoke/pvpoke#285]
Replication:
Navigate to /rankings (defaults to Great League) [format A]
Before the pokemon list has fully populated, select Willpower Cup (or another option) [format B]
When format B is selected, the site clears the pokemon list, and starts to add pokemon for format B. However, any pokemon that had not loaded in format A are now added to the list.
The pokemon list will now show a mixture of pokemon from format A and B.
Various bits of the interface are then no longer usable such as the text search, or navigating to a different format now shows no pokemon in the list.

I can replicate consistently on my Android (Samsung S22) where loading is slower, even when using Performance mode.
I can't replicate on my laptop where loading is quicker.

Workaround - refresh the page, wait a few extra seconds when the page loads.

I know the workaround seems simple but I've spent long enough looking into what was happening that I thought it worth reporting.

I've never noticed this before a few days ago so commit d9039f8 a few days ago seems suspicious? 
Update: Had a quick look, I don't think we want an interval of i on line 249 on RankingInterface.js, and the problem is that data is being added to the rankings before it's finished executing.

![SmartSelect_20241104_183027_Chrome](https://github.com/user-attachments/assets/1bfbea86-4162-43b5-b223-e9dd6c648c07)
![SmartSelect_20241104_183047_Chrome](https://github.com/user-attachments/assets/02800ccd-3895-4c52-803a-8bd691189b8d)
![SmartSelect_20241104_183103_Chrome](https://github.com/user-attachments/assets/d8d05653-fc1f-4e20-87b7-eda589eca28b)

**Comment by ShaPhi7** [comment]
Just replicated on laptop now too - it's not a problem unless people are quick at selecting (which unfortunately, I suspect most people are!)
![Screenshot 2024-11-04 200520](https://github.com/user-attachments/assets/56f7456d-e8f7-4f11-9845-8d170522413c)

**Comment by pvpoke** [comment]
Thanks for the issue report and the fix! I have it merged and deployed. Let me know if you encounter anything else!
