### ISSUE TITLE
Invalid stats under the tooltip of a pokemon in the ranking page

### ISSUE THREAD

**Issue by anpawo** [pvpoke/pvpoke#289]
url: https://pvpoke.com/rankings/all/1500/overall/blissey/
![image](https://github.com/user-attachments/assets/d51b58d2-5eb6-453d-828c-1d26a0c10bad)

When trying to calculate it on the other side of the website I get different values.

url: https://pvpoke.com/battle/matrix/
![image](https://github.com/user-attachments/assets/7cbf73d4-5911-40d3-b993-87d3503740d2)

Maybe it's meant to be like that, you may be showing some other data on the ranking site. Let me know (pls) if it was an error or just the expected values.

Have a good day.

ps. nice website, it's very clean and nice to use.

**Comment by anpawo** [comment]
btw, i've tried calculating it on my side and i get the values from the second screenshot (matrix page).

**Comment by pvpoke** [comment]
Hey, thanks for the post! The stats shown in the rankings aren't for the rank 1 version of the Pokemon but for a set of "default IV's" which the site uses for all of the simulations. Sorry for the confusion!
