### ISSUE TITLE
Possible to sim against opponent with no charge moves

### ISSUE THREAD

**Issue by Sigafoos** [pvpoke/pvpoke#29]
https://pvpoke.com/battle/multi/1500/all/wobbuffet/00/0-1-0/0-0/

This sims wob -- definitely the OP beast of great league now! -- only losing 31 matchups in all of GL.

I tried to break the url in other ways (give myself 3 shields, etc) but (sadly?) the defaults were used.

**Comment by pvpoke** [comment]
This is a time where I actually get to say it's not a bug, it's a feature! Battling against opponents with 0 Charged Moves - while not actually possible in-game - can be helpful to see which Pokemon can farm you for energy by utilizing Fast Moves only.

**Comment by Sigafoos** [comment]
Ah, cool! Makes sense.
