### ISSUE TITLE
Sableye's IV pool is incomplete

### ISSUE THREAD

**Issue by DanielMLeal78** [pvpoke/pvpoke#294]
Hi! Sableye has a incomplete IV pool, the 0 and 1 attack IV's are missing from the pool for some reason.
There are only 2744 available IV combos of the 4096 possible.

**Comment by pvpoke** [comment]
Thanks for posting! This is intended for Pokemon which have Return selected as one of their attacks (Purified Pokemon gain +2 to each IV). Although note that it's possible to obtain a Purified Sableye with 0 or 1 IV's through trade. As a workaround, you can remove Return from its selected attacks to see results from the full 4096 combinations.
