### ISSUE TITLE
Unova stats

### ISSUE THREAD

**Issue by efenderbosch** [pvpoke/pvpoke#36]
How to you populate your version of gamemaster.json? Can we generate stats until they hit the real game master?

**Comment by davidpeden3** [comment]
at the beginning of this year, i wrote an app to generate the gamemaster.json from the actual gamemaster to save @pvpoke time. i haven't run it in a while but told matt that i would try to get it back into shape in time for the update. here is the repo in case you're interested:

https://github.com/davidpeden3/pvpoke-gamemaster-adapter

**Comment by efenderbosch** [comment]
Ok, I ended up writing a little utility to pull MSG stats from https://pokeapi.co/

Sometimes my rounding is off by one or two, though.

https://gist.github.com/efenderbosch/2c79130a1feab705b147c477b5d7c7ac
