### ISSUE TITLE
Suggestion/Request: Randomize Button For Pokemon Selection

### ISSUE THREAD

**Issue by fortepc** [pvpoke/pvpoke#4]
Sometimes you don't have a specific opponent to simulate, sometimes you just want to see how your Pokemon works against a bunch of random opponents. Other times maybe you want to randomize the entire battle just to try to stumble across something unexpected. 

It would be nice to see the battle simulator and team builder to have a "Random" button to randomize the species selection, and maybe a "Randomize All" button to randomly select all the Pokemon selection slots currently on screen if you wanted to randomize both pokemon in a battle simulation, or your entire team in the team builder.

**Comment by pvpoke** [comment]
Thanks for the suggestion! That sounds like a fun option and should be easy to implement.

**Comment by pvpoke** [comment]
Happy to report this has been added in the latest release! There's now a "Random" button above the Pokemon selection. There isn't a "randomize all" button yet on the Team Builder page yet so you'll have to randomize those individually, but that's a good idea too.

**Comment by fortepc** [comment]
Works for me!
