### ISSUE TITLE
Missing Pokemon for Timeless Cup rankings

### ISSUE THREAD

**Issue by wilkinson** [pvpoke/pvpoke#40]
Many, many Pokemon are missing from the [Timeless Cup Rankings](https://pvpoke.com/rankings/timeless/1500/overall/), such as Caterpie, Kakuna, Weedle, Kakuna, Ekans, Pikachu... I noticed because my own starter as a kid was a Pikachu from Pokemon Yellow. I've looked through the `src/data/gamemaster.json` file and `src/data/rankingoverrides.json`, but I haven't found the code where these Pokemon are filtered out. Where does this occur? Is this the intended behavior?

**Comment by pvpoke** [comment]
Thanks for posting! This is intended behavior - to streamline the ranking process, I exclude Pokemon like Pikachu, Kakuna, etc. that don't meet certain stat requirements and wouldn't be considered for typical play. This filtering occurs in the `generateFilteredPokemonList()` function of `js/GameMaster.js`.

Outside of the rankings, you can use the Multi-Battle tool to see how any Pokemon performs against the cup:

https://pvpoke.com/battle/multi/1500/timeless/pikachu/11/2-5-2/2-1/

**Comment by wilkinson** [comment]
That makes sense, thank you very much!
