### ISSUE TITLE
global forcePickStrategy is unused?

### ISSUE THREAD

**Issue by nrkn** [pvpoke/pvpoke#52]
https://github.com/pvpoke/pvpoke/search?q=forcePickStrategy&unscoped_q=forcePickStrategy

It's referenced twice but the only place it's set is here? And it doesn't appear to do anything?

https://github.com/pvpoke/pvpoke/blob/78ca75a6c3ebef280f48290d7fafde8c80e7edc8/src/js/training/MatchHandler.js#L90

**Comment by pvpoke** [comment]
Good find! This was a holdover from when I had the "replay" function utilize the "SAME_TEAM" pick strategy at some point in development. It doesn't work this way anymore, so I've removed this and other references in an upcoming commit.
