### ISSUE TITLE
Incorrect data for darumaka

### ISSUE THREAD

**Issue by Fly33** [pvpoke/pvpoke#53]
Pokemon.js?v=1.12.34.0:737 Uncaught TypeError: Cannot read property 'moveId' of undefined
    at Pokemon.selectRecommendedMoveset (Pokemon.js?v=1.12.34.0:737)
    at rankerObject.rank (TeamRanker.js?v=1.12.34.0:116)
    at interfaceObject.generateMultiBattleResults (Interface.js?v=1.12.34.0:824)
    at Interface.js?v=1.12.34.0:1647
![Screenshot_39](https://user-images.githubusercontent.com/6317897/74591620-77fae000-502a-11ea-8681-69850cc438e2.png)
![Screenshot_38](https://user-images.githubusercontent.com/6317897/74591623-7f21ee00-502a-11ea-8c53-79b1429a3bac.png)

**Comment by pvpoke** [comment]
Thanks for this! I removed Psychic from Darumaka's movepool so I need to regenerate the move usage data for Darumaka when I get the chance.

**Comment by pvpoke** [comment]
I have this fixed now, the Gen 5 rankings should work as expected.
