### ISSUE TITLE
Typing of Fast Move isn't color coded in Team Builder

### ISSUE THREAD

**Issue by fortepc** [pvpoke/pvpoke#6]
I noticed the charge moves are color coded, but the fast moves aren't. Thought I should bring this to attention.

**Comment by fortepc** [comment]
Maybe just a separation line? Or maybe add type symbols to the mix instead of color coding them?

**Comment by pvpoke** [comment]
In [v1.3.0](https://github.com/pvpoke/pvpoke/releases/tag/v1.3.0), I've separated Fast Moves and Charged Moves and applied the same styling to the Fast Move dropdown as the Charged Move ones.
