### ISSUE TITLE
Styling issue with Ranking sub-menu

### ISSUE THREAD

**Issue by noahfkaplan** [pvpoke/pvpoke#66]
Currently the ranking icon overlaps with the "Custom Rankings" text in the Ranking sub-menu. I was looking into resolving this and wanted to ask about the size of the icon while I am in that area of the code. It seems that the size of the icon is determined by the height of the sub-menu option and with "Custom Rankings" being the only sub-menu text that wraps to 2 lines, the icon for that sub-menu option is twice the size of the other sub-menu options. 
![image](https://user-images.githubusercontent.com/14228573/80543345-a840f200-897c-11ea-9ed4-9f1a19b35920.png)

I think there are a few solutions for this, with the one I'm leaning toward being to make the icon the same size as if it were a single line menu option and centering it vertically.  Is this implementation something that fits the styling of the project, or would a different approach be preferred?

**Comment by noahfkaplan** [comment]
I tried out a few options, and I think the one that looks best is to extend the max-width of the sub-menu and prevent the option text from wrapping. The implementation I mentioned in my last message looked awkward. 
![image](https://user-images.githubusercontent.com/14228573/80521595-48851f80-8959-11ea-83b3-e14efa84e70d.png)
(ignore the "fake option", was verify it still looked good with multiple sub-menu options)

Let me know if that looks ok, and if so, I'll go ahead and put in a PR.

**Comment by pvpoke** [comment]
Thanks for reporting this! Sorry I haven't been able to reply sooner, it's been a wild few days. Go ahead and submit a PR and I'll take a look!

**Comment by pvpoke** [comment]
Thanks for helping me resolve this issue! Can I cite you in the update notes?

**Comment by noahfkaplan** [comment]
Sure! Thanks for the responsiveness and helping me get it integrated.

**Comment by pvpoke** [comment]
The update for this has now been deployed. Thanks for your help!
