### ISSUE TITLE
Loading Saved Teams in Train sticks to Great League versions

### ISSUE THREAD

**Issue by comagt** [pvpoke/pvpoke#69]
Howdy, 

Even though I load and save an ultra team, if I go over to the train page and select it. The team will enter the simulator with Great stats.  I confirmed that the CP shown on each pokemon is Ultra values and even hit save changes.  However, when the fight actually starts the team is steamrolled by the opponent because they have CP 1500 vs 2500 values.  Maybe I am missing something but I have tried to check and fiddle with all the options. I have to manually delete and add them back to get the right CP values.

Thank you for everything you do!

**Comment by noahfkaplan** [comment]
Looking at how teams are saved, it looks like only the pokemon's names and selected moves are saved. CPs are then calculated when the team is loaded in. If you select ultra league from the drop-down in training mode **before** loading in your saved team, it should calculate the CPs for ultra league correctly. Not sure if there are plans to change how that is saved at some point, but that work-around should make saving and loading teams better for you in the meantime.
![image](https://user-images.githubusercontent.com/14228573/81081132-86d19000-8ebf-11ea-8c84-8d1b33c37f1b.png)

**Comment by comagt** [comment]
Awesome and thank you for the response!  I gave this a shot, but it appears that multiselect is not adjusting all values but just the first Pokémon in the list.

**Comment by pvpoke** [comment]
Thanks for posting this! I'll look into why this isn't adjusting.

**Comment by noahfkaplan** [comment]
I was playing around with a fix locally where I call "setCP" on the multiselector when the league drop-down is updated. Seems to be working, but I need to do some additional testing. Do you see anything flawed with that approach?

**Comment by pvpoke** [comment]
Sounds good to me! Here's what should work for adjusting both the player's team and the bot's team, if manually set:

`// Update team CPs
for(var i = 0; i < multiSelectors.length; i++){
	multiSelectors[i].setCP(cp);
}`

Want to submit a PR? Otherwise it's simple enough for me to add, either way works.

**Comment by noahfkaplan** [comment]
yeah, I'll submit a PR since I've got a branch set up. Should be in the next few minutes. Thanks for looking into this.

**Comment by pvpoke** [comment]
Thanks so much for your help! I have this merged and deployed now.

**Comment by comagt** [comment]
Holy cow you guys are awesome!! Thank you so much.
