### ISSUE TITLE
HP Grass dealing SE damage to Qwilfish

### ISSUE THREAD

**Issue by Nelagend** [pvpoke/pvpoke#7]
Observed in Qwilfish v Togekiss in Twilight League cup - HP Grass deals 12 damage like the SE types of Electric/Psychic/Ground, rather than the 8 damage done by other neutral types.  (Grass is SE vs Water and NVE vs Poison, so Poison's grass resistance in general might be missing.)

**Comment by Nelagend** [comment]
Just checked in a Qwilfish v Venusaur matchup - Vine Whip and Frenzy Plant both deal SE damage, so it looks like this is a Grass v Poison miss rather than a Hidden Power specific issue.

**Comment by pvpoke** [comment]
Thanks so much for the report, Nelagend. You're correct that Poison was missing its resistance to Grass. This has been fixed in the latest release and the rankings have been updated accordingly. Thank you!
