### ISSUE TITLE
Battle: Baiting with Power-up punch

### ISSUE THREAD

**Issue by noahfkaplan** [pvpoke/pvpoke#73]
Currently, if a pokemon knows power-up punch and the "Bait shields with low-energy moves" option is selected, the other pokemon will not shield the first charged move. This leads to the power-up punch user to continue to use power-up punch even if their other charged move is super effective. The other pokemon will continue to not shield, until the last power-up punch is used. This makes some sense, since the last power-up punch will deal the most damage, however, it changes the results of a number of match-ups that imo would never be played out this way by a human.

An example of this is Scrafty vs Giratina Altered in Ultra league:
How it works currently:
https://pvpoke.com/battle/2500/scrafty/giratina_altered/11/0-3-2/1-2-3/
How I think it should work:
https://pvpoke.com/battle/sandbox/2500/scrafty/giratina_altered/22/0-3-2/1-2-3/11.110100-14.100100-19.110000-24.101000-29.110000-36.101000/

This also swings the 1 shield match-up between Medicham and Altaria to Altaria's favor in the great league.

**Comment by pvpoke** [comment]
Thanks for the post! Originally I didn't have any special cases built around moves like Power-Up Punch and Acid Spray. When the default behavior was to draw a shield every time, Pokemon with these moves gained a lot of unrealistic wins. In Altaria vs Medicham for example, seasoned Altaria players are never going to shield the first Charged Move.

Now what happens is Pokemon don't shield PUP or Acid Spray unless the accompanying move threatens a certain percentage of their HP. With baiting turned on, Pokemon with PUP or Acid Spray will attempt to bait until they successfully draw the shield.

I plan to keep the special shielding cases for PUP and Acid Spray, but I would like to make more behavior options such as a "smart bait" setting where PUP users won't bait if the opponent is programmed to not fall for the bait, for example.

**Comment by noahfkaplan** [comment]
That makes sense. I was just looking at the battle logic around PUP and Acid Spray, and accounting for the scenario above seems pretty tricky at the moment. I'll go ahead and close out this issue. Thanks for the discussion!
