### ISSUE TITLE
Premier Cup Rankings differ from Custom Cup Rankings with identical configuration.

### ISSUE THREAD

**Issue by alexameen** [pvpoke/pvpoke#78]
Steps to reproduce:

Custom Rankings > Master League > Add Exclusion Filter > Legendary, Mythical > Simulate
Rankings > Master League > Premier Cup

This may be intentional to account for better baiting, etc; but I thought I would at least point it out in case it was accidental.

**Comment by pvpoke** [comment]
Hey, thanks for posting this. The Custom Rankings is a more streamlined version of the full rankings and doesn't run the same categories or weight matchups against specific Pokemon the same. I would like to expand the Custom Rankings with more options so these are more similar.
