### ISSUE TITLE
Default IVs for Galarian Farfetch'd are incorrect

### ISSUE THREAD

**Issue by jgmcelwain** [pvpoke/pvpoke#81]
https://github.com/pvpoke/pvpoke/blob/eeeb1f5f94fdcd80c43aa8d868576a875d016635/src/data/gamemaster.json#L2825

Since G-Farfetch'd has different base stats to K-Farfetch'd a 15/15/15 spread goes over 1500cp. 

This appears to be affecting rankings - currently says it [beats Azumarill in the 1s](https://pvpoke.com/battle/1500/farfetchd_galarian/azumarill/11/0-3-2/0-2-1/), but if you change the IVs to [legal rank 1](https://pvpoke.com/battle/1500/farfetchd_galarian-38-0-15-15-4-4-1/azumarill/11/0-3-2/0-2-1/) it loses.

**Comment by pvpoke** [comment]
Thank you! I have this resolved now in the latest update.
