### ISSUE TITLE
Question: why do some pokemon not show up in the list at all?

### ISSUE THREAD

**Issue by davidpeden3** [pvpoke/pvpoke#9]
E.g., I wanted to take a look at Kirlia. I see that it exists [here](https://github.com/pvpoke/pvpoke/blob/master/src/data/gamemaster.json#L5197-L5216) but is missing moves. Is that why it doesn't show up in the UI?

**Comment by davidpeden3** [comment]
Thanks for confirming my suspicion. A PR that solves this specific issue is easy enough but it's worrisome that because your file (currently) requires manual effort to generate that this problem may occur again in the future if the actual game master file changes and you need to adapt to it (again).

I guess it's outside of the scope of this specific issue, but I'd be interested to know more about your "dumb reasons". I wonder if it would be easier to just write an adapter of the main file to your desired output.

That begs the question, though, why can't you use it as is?

**Comment by pvpoke** [comment]
The file I'm using is a carryover from a different project of mine, where I only needed a small selection of Pokemon. It works but obviously there are maintenance issues as you pointed out.

The original game master file is 2 MB and contains a lot of unnecessary data related to things like avatar items, badges, Pokemon genders and sizes, etc. An adapter would be ideal! A CP rebalance, move rebalance, or a new generation of Pokemon would all be problematic for the current setup.

**Comment by davidpeden3** [comment]
Cool, I'll play with creating one. We'll see if it proves to be valuable, and if so, how to integrate it into your flow.

**Comment by davidpeden3** [comment]
@pvpoke Do you have a slack channel, discord, etc. that I could join and chat with you about some stuff. I've written the basic adapter but have some questions for you about your file format.

Seems like this effort is timely with the changes that just dropped!

**Comment by pvpoke** [comment]
Indeed! :) I don't have anything really official set up but this Discord has a channel for me [here](https://discord.gg/6Ufkcd]. My username is KakunaMattata42.

**Comment by davidpeden3** [comment]
I tried the link and it says the invite is invalid (either expired or unauthorized). Feel free to come join the Austin, TX server: 

https://discord.gg/ypgK8PP

I'm Confusion135 on there.

**Comment by pvpoke** [comment]
Thank you! Just joined the server. Feel free to DM me or tag me in whichever channel would be best.
